<?php


/**
 * Implements hook_menu().
 */
function loan_calculator_menu() {
  $items['loan-calculator'] = array(
    'title' => 'Loan Calculator',
    'page callback' => 'loan_calculator_page',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_menu() callback
 */
function loan_calculator_page() {
    return theme('loan_calculator_template');
}

/**
 * Implements hook_theme().
 */
function loan_calculator_theme($existing, $type, $theme, $path) {
  return array(
      'loan_calculator_template' => array(
          'template' => 'templates/loan_calculator',
      ),
  );
}
