<?php

/**
 * @file export_pdf_ajax.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_menu().
 */
function export_pdf_ajax_menu() {
    $items['export-pdf-ajax/%'] = array(
        'title' => 'Export PDF',
        'page callback' => 'export_pdf_ajax_page',
        'page arguments' => array(1),
        'access callback' => TRUE,
    );

  return $items;
}

/**
 * hook_menu() callback
 *
 * @param $html
 * @return string
 */
function export_pdf_ajax_page($html) {

    $pdf = tcpdf_get_instance();

    $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

    $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
    $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

    $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

    $pdf->SetFont('helvetica', '', 11);

    $pdf->AddPage();

    $pdf->writeHTML($html);

    $pdf->Output('graph.pdf', 'D');

}












