<?php

/**
 * Implements hook_menu
 */
function physical_entity_current_deposit_menu()
{
    $items['physical-entities/add-deposit'] = array(
        'title' => 'Add Deposit',
        'page callback' => 'physical_entity_current_deposit_page',
        'access callback' => TRUE,
    );

    return $items;
}

/**
 * hook_menu() callback
 *
 * @return string
 */
function physical_entity_current_deposit_page()
{
//    $loan_statement = physical_entity_form_statement_get_statement_form_by_nid(48);
//    print $loan_statement->field_issue_date['und'][0]['value'];
//    exit;
    return drupal_get_form('physical_entity_current_deposit_form');
}

/**
 * @Implements the hook_form()
 *
 * @param $form
 * @param $form_state
 * @return mixed
 */
function physical_entity_current_deposit_form($form, &$form_state)
{
    $physical_entities_obj = get_physical_entities_with_issued_loans();
    $physical_entities = array();
    $personal_id_numbers = array();

    foreach($physical_entities_obj as $physical_entity_obj) {
        $physical_entities[$physical_entity_obj->nid] =
            $physical_entity_obj->field_first_name['und'][0]['value'] . ' '.$physical_entity_obj->field_last_name['und'][0]['value'];

        $personal_id_numbers[$physical_entity_obj->nid] = $physical_entity_obj->field_personal_id_number['und'][0]['value'];
    }

    $form['#prefix'] = '<div class="col-lg-4">';
    $form['#suffix'] = '</div>';

    $form['personal_id_number_input'] = array(
        '#type' => 'textfield',
        '#title' => t('Personal ID Numbers'),
        '#maxlength' => 11,
        '#default' => '',
    );

    $form['personal_id_numbers'] = array(
        '#type' => 'select',
        '#options' => $personal_id_numbers,
//        '#required' => TRUE,
        '#default' => '',
    );


    $form['physical_entity'] = array(
        '#type' => 'select',
        '#title' => t('Physical Entities'),
        '#options' => $physical_entities,
        '#required' => TRUE,
        '#default' => '',
    );

    $currency = array(
        'USD' => 'USD',
        'GEL' => 'GEL',
    );

    $form['currency'] = array(
        '#type' => 'select',
        '#title' => t('Currency'),
        '#options' => $currency,
//        '#required' => TRUE,
        '#default' => 'GEL',
    );

    $form['amount'] = array(
        '#type' => 'textfield',
        '#title' => t('Amount'),
//        '#required' => TRUE,
        '#default' => '',
    );

    $form['date'] = array(
        '#type' => 'date_popup',
        '#title' => t('Date'),
        '#date_label_position' => 'within',
        '#date_format' => 'Y-m-d',
        '#default' => date('Y-m-d')
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );

    return $form;
}


/**
 * Implements hook_form_submit()
 *
 * @param $form
 * @param $form_state
 */
function physical_entity_current_deposit_form_submit($form, &$form_state)
{
    $node = new stdClass();
    $node->type = 'actual_deposits';
    $physical_entity_nid = $form_state['values']['physical_entity'];
    $physical_entity = physical_entity_create_get_physical_entity_by_nid($physical_entity_nid);
    $node->title = $physical_entity->title;
    node_object_prepare($node);

    $node->language = LANGUAGE_NONE;

    $node->field_physical_entity[$node->language][] = array(
        'target_id' => $physical_entity_nid,
        'target_type' => 'node',
    );

    $node->field_currency[$node->language] = array(
        0 => array('value' => $form_state['values']['currency'])
    );

    $node->field_amount[$node->language] = array(
        0 => array('value' => $form_state['values']['amount'])
    );

    $node->field_date[$node->language] = array(
        0 => array('value' => $form_state['values']['date'])
    );

    $node = node_submit($node);
    node_save($node);

    drupal_set_message("Actual deposit successfully saved");
}

function get_physical_entities_with_issued_loans() {
    $query = new EntityFieldQuery();

    $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'physical_entity_loan')
        ->fieldCondition('field_loan_status', 'target_id', physical_entity_form_statement_get_loan_status_id('Issued'), '=');
    $result = $query->execute();

    $statement_forms = array();

    if (isset($result['node'])) {
        $statement_forms = entity_load('node', array_keys($result['node']));
    }

    $physical_entity_ids = array();
    $physical_entities = array();

    foreach($statement_forms as $form) {
        array_push($physical_entity_ids, $form->field_physical_entity['und'][0]['target_id']);
    }

    $query = new EntityFieldQuery();

    $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'physical_entity')
        ->propertyCondition('nid', $physical_entity_ids, 'IN');
    $result = $query->execute();

    if (isset($result['node'])) {
        $physical_entities = entity_load('node', array_keys($result['node']));
    }


    return $physical_entities;
}